### ISSUE TITLE
Detecting duplicate sequence name

### ISSUE THREAD

**Issue by MikeFreyberger** [aaugustin/django-sequences#25]
Is there an established way to ensure a "new" sequence isn't created with the same sequence name? I'm mainly thinking about the case of a large code base with a lot of contributors.

**Comment by aaugustin** [comment]
That's a good question :-)

Given that sequences are initialized implicitly when asking the first value, indeed, a conflict is possible.

I wouldn't expect a single project to use a ton of sequences: in a given business, there's only so many things for which you want strictly sequential numbers. But perhaps I'm unaware of some use cases.

At this point I think the answer is:

- Look in your production admin if the sequence name already exists
- Run a "Find All" on the sequence name in your source code (but you could miss a conflict if an enterprising engineer felt creative with dynamically generated sequence names)

**Comment by vitorfs** [comment]
You could centralize the sequence names in a single file using constants, and whenever you call `get_next_value` you use the constant instead of hard coding the sequence name

Something like

```python
class ProjectSequences:
    INVOICE_NUMBERS = "invoice_numbers"
    CASE_NUMBERS = "case_numbers"
```

Then

```python
get_next_value(ProjectSequences.INVOICE_NUMBERS)
```

That way you will always need to refer to the `ProjectSequences` to "create" a new sequence. Then you could also write a Django system check to introspect the `ProjectSequences` class and check for duplicates

**Comment by aaugustin** [comment]
At this point we have no plan to make changes in django-sequences and several alternative proposals. I'm going to close the issue.

**Comment by MikeFreyberger** [comment]
All this makes sense. Thank you!!
